name: 2-hashtag-dapp

# The toolstack used to build the application.
type: nodejs:10

# Configuration of the build of this application.
build:
    flavor: none

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: |
            echo "config = $(echo $PLATFORM_VARIABLES | base64 -d)" > /tmp/config.js
            sleep infinity
    # Specific parameters for different URL prefixes.
    locations:
        "/":
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            # Folder name is set in npm run buildenvvar.
            root: "dist"
            index:
                - "index.html"
            passthru: /index.html

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            
            expires: 300s
            scripts: true

            # Deny access to static files in this location.
            allow: false
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
                    allow: true
                ^/robots\.txt$:
                    allow: true

        "/docs":
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            # Folder name is set in npm run buildenvvar.
            root: "shared/docs"
            index:
                - "index.html"
            passthru: /index.html

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 1h
            scripts: false
            rules:
                # Restrict access to markdown (.md) files.
                \.(md|txt)$:
                    allow: true
                ^/robots\.txt$:
                    allow: false

disk: 512

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  '/.tmp_platformsh':
    source: local
    source_path: files/tmp_platformsh
  '/shared':
    source: service
    service: shared
    source_path: shared

# Build dependencies
dependencies:
  nodejs:
    yarn: "*"
    babel-eslint: '10.0.3'
    eslint: '6.7.2'
    eslint-plugin-vue: '6.1.2'
    eslint-config-prettier: '2.9.0'
    eslint-plugin-prettier: '2.6.2'
    prettier: '1.14.0'
    sass-lint: '1.12.1'
    stylelint: '13.2.1'
    stylelint-checkstyle-formatter: '0.1.1'
    stylelint-config-recommended-scss: '4.2.0'
    stylelint-config-standard: '20.0.0'
    stylelint-processor-html: '1.0.0'
    stylelint-scss: '3.16.0'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      set -e
      yarn install
      yarn build

      # Building on platform.sh
      if [ -d /app/.global ]; then
        echo "--------------------------------------------------"
        echo "Symlink /tmp/config.js to dist/config.js"
        echo "--------------------------------------------------"
        ln -fs /tmp/config.js dist/config.js
      fi

      # Building locally.
      if ! [ -d /app/.global ]; then
        echo "----------------------------------------------"
        echo "Move raw markdown documents from hashtag-docs"
        echo "----------------------------------------------"
        # Move raw markdown documents from hashtag-docs.
        ./scripts/pull-docs.sh
      fi

    # The deploy hook runs after your application has been deployed and started.
    deploy: |
      # Deploying on platform.sh
      if [ -d /app/.global ]; then
        echo "----------------------------------------------"
        echo "Putting PLATFORM_VARIABLES into /tmp/config.js"
        echo "----------------------------------------------"
        echo "config = $(echo $PLATFORM_VARIABLES | base64 -d)" >| /tmp/config.js
      fi
