# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: hashtag-api

# The runtime the application uses.
type: nodejs:14

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: "node index.js"

  # Specific parameters for different URL prefixes.
  locations:
      "/public/images":
          # The folder from which to serve static assets, for this location.
          #
          # This is a filesystem path, relative to the application root.
          # Folder name is set in npm run buildenvvar.
          root: "public/images"
          passthru: false

          # How long to allow static assets from this location to be cached.
          #
          # Can be a time in seconds, or -1 for no caching. Times can be
          # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
          # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
          # 365 days).
          expires: 1h
          scripts: false
          rules:
              # Restrict access to markdown (.png) files.
              \.(png)$:
                  allow: true
              ^/robots\.txt$:
                  allow: false

relationships:
  chromeheadlessbrowser: "headlessbrowser:http"

# The size of the persistent disk of the application (in MB).
disk: 512

mounts:
  '/public/images':
    source: local
    source_path: images
